catinc/Controllers/ProductController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using catinc.Models.Domain;
using catinc.Models.MemberSystem;
using catinc.Models.ViewModels.ProductViewModels;
using catinc.Models.ViewModels.VendorViewModels;
using catinc.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace catinc.Controllers
{
    /// <summary>
    /// Product controller to deal with products
    /// </summary>
    [Authorize]
    [Route("[controller]/[action]")]
    public class ProductController : Controller
    {
        private ILogger _logger;
        private IProductRepository<Product> _productRepository;
        private IVendorRepository<Vendor> _vendorRepository;

        /// <summary>
        /// Creates the product controller
        /// </summary>
        /// <param name="productRepository"></param>
        /// <param name="vendorRepository"></param>
        /// <param name="logger"></param>
        public ProductController(IProductRepository<Product> productRepository, IVendorRepository<Vendor> vendorRepository, ILogger<VendorController> logger)
        {
            _productRepository = productRepository;
            _vendorRepository = vendorRepository;
            _logger = logger;
        }

        /// <summary>
        /// Returens the create product page
        /// </summary>
        /// <param name="returnURL"></param>
        /// <returns></returns>
        [HttpGet]
        // [AllowAnonymous]
        public IActionResult CreateProduct(string returnURL = null)
        {
            ViewData["ReturnURL"] = returnURL;
            return View();
        }

        /// <summary>
        /// Submits the create product model to create a product
        /// </summary>
        /// <param name="model"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        [HttpPost]
        // [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public Task<IActionResult> CreateProduct(CreateProductViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                string userIdValue = "";
                if (User != null)
                {
                    var claimsIdentity = User.Identity as ClaimsIdentity;
                    if (claimsIdentity != null)
                    {
                        var userIdClaim = claimsIdentity.Claims
                            .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                        if (userIdClaim != null)
                        {
                            userIdValue = userIdClaim.Value;
                        }
                    }
                }
                // model.UserName = User.Identity.Name;
                var result = _vendorRepository.FindByUserID(userIdValue).Result;
                if (result != null)
                {
                    _productRepository.Create(model, result);
                    _logger.LogInformation("Product created.");

                    return Task.Run(() => RedirectToLocal("/home/index"));
                }
                // AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            // return Task.Run(() => View(model));
            return null;
        }

        #region Helpers

        // private void AddErrors(Result result)
        // {
        //     foreach (var error in result.Errors)
        //     {
        //         ModelState.AddModelError(string.Empty, error.Description);
        //     }
        // }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        #endregion
    }
}

catinc/Controllers/VendorController.cs
using System.Threading.Tasks;
using catinc.Models.Domain;
using catinc.Models.MemberSystem;
using catinc.Models.ViewModels.VendorViewModels;
using catinc.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using catinc.Models.Util;

namespace catinc.Controllers
{
    /// <summary>
    /// Vendor controller to deal with vendors
    /// </summary>
    [Authorize]
    [Route("[controller]/[action]")]
    public class VendorController : Controller
    {
        private ILogger _logger;
        private IVendorRepository<Vendor> _vendorRepository;

        /// <summary>
        /// Creates a vendor controller
        /// </summary>
        /// <param name="vendorRepository"></param>
        /// <param name="logger"></param>
        public VendorController(IVendorRepository<Vendor> vendorRepository, ILogger<VendorController> logger)
        {
            _vendorRepository = vendorRepository;
            _logger = logger;
        }

        /// <summary>
        /// Returns the register vendor page
        /// </summary>
        /// <param name="returnURL"></param>
        /// <returns></returns>
        [HttpGet]
        // [AllowAnonymous]
        public IActionResult RegisterVendor(string returnURL = null)
        {
            ViewData["ReturnURL"] = returnURL;
            return View();
        }

        /// <summary>
        /// Submits the register vendor model to create a vendor
        /// </summary>
        /// <param name="model"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        [HttpPost]
        // [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterVendor(RegisterVendorViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                model.UserName = User.Identity.Name;
                var result = _vendorRepository.Create(model, HttpContext.User);
                if (result == Result.Success)
                {
                    _logger.LogInformation("User created a new account with password.");
                    var user = await _vendorRepository.FindByNameAsync(model.VendorName);

                    _logger.LogInformation("User created a new Vendor.");
                    return RedirectToLocal("/home/index");
                }
                // AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        #region Helpers

        // private void AddErrors(Result result)
        // {
        //     foreach (var error in result.Errors)
        //     {
        //         ModelState.AddModelError(string.Empty, error.Description);
        //     }
        // }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        #endregion
    }
}

catinc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="vendor">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cat Inc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div id="vendorName" class="navbar-header" ng-controller="VendorController as vendor"> <!-- ng-app="app" ng-controller="VendorController as vendor" -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">{{vendor.vendorName}}</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Vendor" asp-action="RegisterVendor">Register Vendor</a></li>
                    <li><a asp-area="" asp-controller="Product" asp-action="CreateProduct">Add Product</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer">
            <p>&copy; 2018 - Cat Inc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.9/angular-route.js"></script>
        <script type="text/javascript" src="~/Scripts/vendor.js"></script>
        <script type="text/javascript" src="~/Scripts/store.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
        <script type="text/javascript" src="~/Scripts/store.js" asp-fallback-src="~/js/store.js"></script>
        <script type="text/javascript" src="~/Scripts/vendor.js" asp-fallback-src="~/js/vendor.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>